#!/bin/bash
set -ex

git remote set-branches --add origin $TRAVIS_BRANCH
git fetch

if [[ ( "$TRAVIS_PULL_REQUEST" != "false" ) && ( "$TEST_SUITE" == "lint" ) ]]; then
  # Run cardboardlinter, in case of pull requests
  cardboardlinter --refspec origin/$TRAVIS_BRANCH -n auto
fi

if [[ "$TEST_SUITE" == "unittest" ]]; then
  # Run tests on all pushes
  pushd tts_namespace
  nosetests TTS.speaker_encoder.tests --nocapture
  nosetests TTS.vocoder.tests --nocapture
  nosetests TTS.tts.tests --nocapture
  nosetests TTS.tts.tf.tests --nocapture
  popd
fi

if [[ "$TEST_SUITE" == "testscripts" ]]; then
  # Test server package
  ./tts/tests/test_server_package.sh
  # test model training scripts
  ./tts/tests/test_tts_train.sh
  ./vocoder/tests/test_vocoder_train.sh
fi
